# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Account', models.CharField(max_length=25, unique=True)),
                ('Password', models.CharField(max_length=25)),
                ('DateTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Describe', models.TextField(max_length=200, null=True)),
                ('State', models.PositiveIntegerField(default=0)),
                ('SendTime', models.DateField(auto_now_add=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36f39e-bb09-11e7-b8c2-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Content', models.TextField(max_length=200)),
                ('IsUse', models.BooleanField(default=True)),
                ('IsAdopt', models.BooleanField(default=False)),
                ('Isreply', models.BooleanField(default=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a371ab0-bb09-11e7-9bf5-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('LastChange', models.DateField(auto_now=True)),
                ('Describe', models.TextField(max_length=200, null=True)),
                ('Name', models.CharField(max_length=20)),
                ('IsUse', models.BooleanField(default=True)),
                ('Img', models.ImageField(upload_to='photos/%Y/%m/%d/user')),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36575f-bb09-11e7-bd24-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creation2ProjectLabel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a367e70-bb09-11e7-b254-2e337a850693', null=True)),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creation2ProjectLabel_Creation_set', to='admina.Creation')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a3741c0-bb09-11e7-a45c-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpApplication',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateField(auto_now_add=True)),
                ('Reply', models.TextField(blank=True, null=True)),
                ('Describe', models.TextField(blank=True, null=True)),
                ('WhatWant', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('IsReplied', models.BooleanField(default=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a37b6f1-bb09-11e7-8f86-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Priority', models.PositiveIntegerField(default=0)),
                ('Type', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('IsRead', models.BooleanField(default=False)),
                ('Content', models.TextField(max_length=200)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36f39f-bb09-11e7-ab79-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36cc8f-bb09-11e7-bbfb-2e337a850693', null=True)),
                ('creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Praise_Creation_set', to='admina.Creation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=20, unique=True)),
                ('Description', models.TextField(max_length=200)),
                ('StartTime', models.DateField(auto_now_add=True)),
                ('EndTime', models.DateField()),
                ('Statue', models.PositiveIntegerField(default=0)),
                ('Number', models.PositiveIntegerField(default=1)),
                ('Img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/project')),
                ('Summary', models.TextField(max_length=200, null=True)),
                ('Progress', models.TextField(max_length=200, null=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a35e22e-bb09-11e7-a543-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project2ProjectLabel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a360940-bb09-11e7-b1ad-2e337a850693', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project2ProjectLabel_Project_set', to='admina.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectLabelName', models.CharField(max_length=20, unique=True)),
                ('IsUse', models.BooleanField(default=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a35e22f-bb09-11e7-9175-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Identity', models.PositiveIntegerField(default=0)),
                ('Evaluate', models.TextField(max_length=200)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36575e-bb09-11e7-ace5-2e337a850693', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectUser_Project_set', to='admina.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.DateField(auto_now_add=True)),
                ('EndTime', models.DateField(null=True)),
                ('Describe', models.TextField(max_length=200)),
                ('State', models.PositiveIntegerField(default=0)),
                ('Times', models.PositiveIntegerField(default=1)),
                ('PredictNumber', models.PositiveIntegerField(default=1)),
                ('RecruitedNumber', models.PositiveIntegerField(default=0)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36a580-bb09-11e7-9a9d-2e337a850693', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recruit_Project_set', to='admina.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Reason', models.TextField(max_length=200)),
                ('ReportDate', models.DateField(auto_now_add=True)),
                ('DealTime', models.DateField(null=True)),
                ('State', models.PositiveIntegerField(default=0)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a3768cf-bb09-11e7-92d4-2e337a850693', null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_Comment_set', to='admina.Comment')),
                ('creation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_Creation_set', to='admina.Creation')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_Project_set', to='admina.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.PositiveIntegerField(default=0)),
                ('Value', models.IntegerField(default=0)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a378fe1-bb09-11e7-a28f-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreChange',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Event', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a37b6f0-bb09-11e7-85dc-2e337a850693', null=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScoreChange_Score_set', to='admina.Score')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=10, unique=True)),
                ('Account', models.CharField(max_length=20, null=True, unique=True)),
                ('PassWord', models.CharField(max_length=20)),
                ('Identity', models.PositiveSmallIntegerField(default=0)),
                ('Sex', models.PositiveSmallIntegerField(default=0)),
                ('Email', models.EmailField(max_length=32, unique=True)),
                ('Score', models.PositiveIntegerField(default=0)),
                ('RegistTime', models.DateField(auto_now_add=True)),
                ('Phone', models.CharField(blank=True, max_length=25, null=True)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/user')),
                ('Introduction', models.TextField(max_length=200, null=True)),
                ('School', models.CharField(max_length=20, null=True)),
                ('Institude', models.CharField(max_length=20, null=True)),
                ('Major', models.CharField(max_length=20, null=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a356d00-bb09-11e7-8210-2e337a850693', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User2UserLabel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a36304f-bb09-11e7-b8c0-2e337a850693', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2UserLabel_User_set', to='admina.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserImageForge',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='photos/user/')),
                ('IsUse', models.BooleanField(default=True)),
                ('UploadDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserImageForge_User_set', to='admina.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLabel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IsUse', models.BooleanField(default=True)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Uuid', models.UUIDField(blank=True, default=b'5a360941-bb09-11e7-89d8-2e337a850693', null=True)),
                ('projectLabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLabel_Project_set', to='admina.ProjectLabel')),
            ],
        ),
        migrations.AddField(
            model_name='user2userlabel',
            name='userLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2UserLabel_UserLabel_set', to='admina.UserLabel'),
        ),
        migrations.AddField(
            model_name='scorechange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScoreChange_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Report_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectUser_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='project2projectlabel',
            name='projectLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project2ProjectLabel_ProjectLabel_set', to='admina.ProjectLabel'),
        ),
        migrations.AddField(
            model_name='praise',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Praise_Project_set', to='admina.Project'),
        ),
        migrations.AddField(
            model_name='praise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Praise_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='praise',
            name='user_prised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Praised_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='helpapplication',
            name='AppliedTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Help_App_Team', to='admina.User'),
        ),
        migrations.AddField(
            model_name='helpapplication',
            name='Applier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Help_App_Applier', to='admina.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='Follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follow_Follower_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follow_Creation_set', to='admina.Creation'),
        ),
        migrations.AddField(
            model_name='follow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follow_Project_set', to='admina.Project'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follow_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='creation2projectlabel',
            name='projectLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creation2ProjectLabel_ProjectLabel_set', to='admina.ProjectLabel'),
        ),
        migrations.AddField(
            model_name='creation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creation_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commited_user_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Creation_set', to='admina.Creation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Project_set', to='admina.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_User_set', to='admina.User'),
        ),
        migrations.AddField(
            model_name='apply',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Apply_Recruit_set', to='admina.Recruit'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Apply_User_set', to='admina.User'),
        ),
    ]
