# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentedId',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d3d5ae-bbe9-11e7-b533-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d423cf-bbe9-11e7-b3ad-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d36080-bbe9-11e7-86ed-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d3878f-bbe9-11e7-aad7-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d44ade-bbe9-11e7-bab7-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d4c00f-bbe9-11e7-8b5d-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d3fcc0-bbe9-11e7-b7c8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d3ae9e-bbe9-11e7-9b07-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d2c440-bbe9-11e7-93ee-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d2eb52-bbe9-11e7-a95c-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d2eb51-bbe9-11e7-baf9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d33970-bbe9-11e7-9891-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Describe',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d38790-bbe9-11e7-9a75-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d471f0-bbe9-11e7-8374-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d471f1-bbe9-11e7-8706-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d49900-bbe9-11e7-98c8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d24f0f-bbe9-11e7-abf2-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d31262-bbe9-11e7-a08f-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='userimageforge',
            name='UploadDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'80d31261-bbe9-11e7-bd48-68f728892930', null=True),
        ),
    ]
