# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0002_auto_20171028_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Describe', models.CharField(blank=True, max_length=70, null=True)),
                ('Priority', models.PositiveIntegerField(default=0)),
                ('Uuid', models.URLField(blank=True, default=b'5599b8df-bfab-11e7-afc9-2e337a850693', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='SendTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5599b8de-bfab-11e7-8b12-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559a0700-bfab-11e7-8d25-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='LastChange',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'55991ca1-bfab-11e7-82ac-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559943b0-bfab-11e7-aeb5-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559a2e0f-bfab-11e7-a0d1-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559aa341-bfab-11e7-bc6f-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5599dfee-bfab-11e7-aefb-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'55996ac1-bfab-11e7-a782-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='EndTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598594f-bfab-11e7-a7b8-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598a771-bfab-11e7-9785-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598a770-bfab-11e7-8b42-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598f590-bfab-11e7-813b-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='EndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='StartTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'55996ac0-bfab-11e7-8ba7-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='DealTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ReportDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559a551e-bfab-11e7-8404-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559a7c30-bfab-11e7-a6a4-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'559aa340-bfab-11e7-920c-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='RegistTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'55980b30-bfab-11e7-b1d6-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598f58f-bfab-11e7-bd75-2e337a850693', null=True),
        ),
        migrations.AlterField(
            model_name='userimageforge',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5598ce80-bfab-11e7-9eed-2e337a850693', null=True),
        ),
    ]
