# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0004_auto_20171103_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ScoreRankName',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f9be2-e166-11e7-8fea-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205fea00-e166-11e7-b37f-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f4dc0-e166-11e7-b743-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f4dc1-e166-11e7-aa38-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2060110f-e166-11e7-8c32-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'20605f2f-e166-11e7-ad80-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205fc2f1-e166-11e7-bca8-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='Uuid',
            field=models.URLField(blank=True, default=b'205fc2f0-e166-11e7-9066-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f9be1-e166-11e7-b313-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='Progress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205ed88f-e166-11e7-b099-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205effa1-e166-11e7-9dcf-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205ed890-e166-11e7-bc10-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Evaluate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f26b1-e166-11e7-9b8d-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Describe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f74d1-e166-11e7-927a-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2060381e-e166-11e7-8515-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2060381f-e166-11e7-b58c-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'20605f2e-e166-11e7-8581-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205eb180-e166-11e7-bdb4-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205f26b0-e166-11e7-9975-002324d725f8', null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'205effa2-e166-11e7-9e57-002324d725f8', null=True),
        ),
    ]
