# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0004_auto_20170922_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='LastChange',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf6b58e-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf6edc4-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf6597c-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf66f5c-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf7099e-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf76a7e-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf6cc36-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf69f40-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf5dda8-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf6013e-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf5f0b8-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf642fc-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf68960-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf72578-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf73cca-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf752be-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf5c43a-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf62e8e-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccf61584-a005-11e7-9dc3-c03fd5f58c28'), null=True),
        ),
    ]
