# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0005_auto_20170923_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d7ac6-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29daf28-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d1c70-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d325a-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29dcb52-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29e2bf6-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d918c-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d62f2-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29c9fca-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29cc478-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29cb3f2-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d04d8-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29d4c36-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29de5ec-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29dfca8-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29e13a0-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29c8698-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29ceffc-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29cd80a-a005-11e7-8ebe-c03fd5f58c28'), null=True),
        ),
    ]
