# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0010_auto_20171014_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc0ffa-b0da-11e7-9d25-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc4c10-b0da-11e7-b335-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb9b8c-b0da-11e7-b995-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edbc1a4-b0da-11e7-a142-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc5f90-b0da-11e7-9e5b-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edcc17a-b0da-11e7-bccc-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc24d4-b0da-11e7-9490-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edbea02-b0da-11e7-a142-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb1164-b0da-11e7-b214-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb3890-b0da-11e7-8277-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='projectLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project2ProjectLabel_ProjectLabel_set', to='admina.ProjectLabel'),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb24f6-b0da-11e7-9e00-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb86e4-b0da-11e7-870f-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edbd53a-b0da-11e7-ad73-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc86b6-b0da-11e7-9dec-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edc9a6e-b0da-11e7-8512-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edcade2-b0da-11e7-a384-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edaea3a-b0da-11e7-b384-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb7350-b0da-11e7-b861-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='userLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2UserLabel_UserLabel_set', to='admina.UserLabel'),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0edb4c24-b0da-11e7-9f33-c85b7634aac6'), null=True),
        ),
    ]
