# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0012_auto_20171026_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimageforge',
            name='ImageName',
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79c8880-ba3f-11e7-8ecb-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79caf90-ba3f-11e7-8570-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79c134f-ba3f-11e7-87c7-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79c1350-ba3f-11e7-b517-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79cd69e-ba3f-11e7-96d8-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79d72e1-ba3f-11e7-85b0-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79caf8f-ba3f-11e7-b74c-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79c616e-ba3f-11e7-947e-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79b5000-ba3f-11e7-9277-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79b9e21-ba3f-11e7-a266-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79b7711-ba3f-11e7-a2ae-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79bec40-ba3f-11e7-bbe7-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Describe',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79c3a5e-ba3f-11e7-9aa3-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79cfdb0-ba3f-11e7-846e-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79d24c0-ba3f-11e7-b124-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79d4bcf-ba3f-11e7-b305-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79b28f0-ba3f-11e7-a1b5-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79bc530-ba3f-11e7-abf6-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='userimageforge',
            name='UploadDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c79b9e22-ba3f-11e7-8406-c85b7634aac6'), null=True),
        ),
    ]
