# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0017_auto_20171026_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimageforge',
            name='ImageName',
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc9fe1-ba37-11e7-9d2a-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbcee00-ba37-11e7-bd2b-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc2ab0-ba37-11e7-984f-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc2ab1-ba37-11e7-8aeb-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbd150f-ba37-11e7-9f02-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbd8a40-ba37-11e7-9616-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbcc6ee-ba37-11e7-8198-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc78d1-ba37-11e7-9cf6-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbb8e70-ba37-11e7-a30a-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbbb580-ba37-11e7-bda3-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbb8e71-ba37-11e7-b920-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc03a1-ba37-11e7-b325-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbc51c0-ba37-11e7-bc80-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbd3c1e-ba37-11e7-a4f4-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbd6330-ba37-11e7-ab2d-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbd6331-ba37-11e7-911d-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbb6761-ba37-11e7-895e-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbbdc90-ba37-11e7-b63f-c85b7634aac6'), null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbbbdc8f-ba37-11e7-8d50-c85b7634aac6'), null=True),
        ),
    ]
